### create orders with user Id
POST http://localhost:9094/shop/v1/orderWithUserId
Content-Type: application/json

{
    "user_id": 1
}

### get orders from a particular user id
GET http://localhost:9094/shop/v1/orders?user_id=1

### create order {add item to cart} 
POST http://localhost:9094/shop/v1/order
Content-Type: application/json

{
    "user_id": 1,
    "product_id": 8
}

### create orders in the cart icon
POST http://localhost:9094/shop/v1/orders-with-userId
Content-Type: application/json

{
    "user_id": 1
}

### delete all order with user id
DELETE http://localhost:9094/shop/v1/deleteOrders?user_id=1

### delete a single order by id
DELETE http://localhost:9094/shop/v1/deleteAnOrder/1


### update an order by id
PATCH  http://localhost:9094/shop/v1/order/1
Content-Type: application/json

{
    "customer_id": 1,
    "price": 500.00,
    "product":"Brazillian Hair"
}


