### get all products
GET http://localhost:9094/shop/v1/products

### route for uploading the product image
POST http://localhost:9094/shop/v1/store-product-image

###add a new product
POST http://localhost:9094/shop/v1/product  

###
POST http://localhost:9094/shop/v1/product 