### get all users
GET http://localhost:9094/shop/v1/allUsers

### register new user
POST http://localhost:9094/shop/v1/user
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@mail.com",
   "password": "userone",
   "profile_photo": "https://media.istockphoto.com/id/450100369/photo/portrait-of-a-businesswoman.jpg?s=612x612&w=0&k=20&c=WK4vKnf6wNGwTqygZ62MzQ_l3fjd4H2ArcOXZ4UJmBY="
}

### login a user
POST http://localhost:9094/shop/v1/login
Content-Type: application/json

{
    "email": "john@mail.com",
   "password": "userone"
}

###
POST http://localhost:9094/shop/v1/store-image
###
GET http://localhost:9094/uploads/user_images/user.jpg


### admin user
GET http://localhost:9094/api/Alladmin


### login admin
POST http://localhost:9094/api/login
Content-Type: application/json

{
    "email": "elle@mail.com",
   "password": "elle444"
}

### register new user
POST http://localhost:9092/shop/v1/user
Content-Type: application/json

{
    "name": "Eva",
    "email": "eva@mail.com",
   "password": "eva11",
   "profile_photo": "https://media.istockphoto.com/id/450100369/photo/portrait-of-a-businesswoman.jpg?s=612x612&w=0&k=20&c=WK4vKnf6wNGwTqygZ62MzQ_l3fjd4H2ArcOXZ4UJmBY="
}

### register google user
POST http://localhost:9094/shop/v1/google-login
Content-Type: application/json

{
    "name": "Vera",
    "email": "vera@gmail.com",
   "picture": "https://media.istockphoto.com/id/450100369/photo/portrait-of-a-businesswoman.jpg?s=612x612&w=0&k=20&c=WK4vKnf6wNGwTqygZ62MzQ_l3fjd4H2ArcOXZ4UJmBY="
}

### register google user
POST http://localhost:9094/shop/v1/google-login
Content-Type: application/json

{
    "name": "Sharon",
    "email": "shar@gmail.com",
   "picture": "https://media.istockphoto.com/id/450100369/photo/portrait-of-a-businesswoman.jpg?s=612x612&w=0&k=20&c=WK4vKnf6wNGwTqygZ62MzQ_l3fjd4H2ArcOXZ4UJmBY="
}

